In [2]:

import numpy as np
import pandas as pd
print(f"Numpy version: {np.__version__}")
print(f"Pandas version: {pd.__version__}")

/root/MscMak2025-IntroductionToPython-1/.venv/lib/python3.12/site-packages/numpy/_core/getlimits.py:552: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)


Numpy version: 2.3.3
Pandas version: 2.3.3


In [3]:
data = pd.Series([0.01, 0.25, 1, 2])
data

0    0.01
1    0.25
2    1.00
3    2.00
dtype: float64

In [ ]:
data1 = pd.Series([0,1,2,3,4,5], 
                  index=['a','b','c','d','e','f'])
data1

In [ ]:
a ={1,2,3,4,5}
b ={2,3,4,6,7,8}
a & b 

In [9]:
disk1 =np.array([10,20,30,40,50])
type(disk1)
print(disk1)
disk2 = np.array([1,2,3,4], dtype='float32')
print(disk2)
disk3 = np.array([10,20,30,44.4])
print(disk3)


[10 20 30 40 50]
[1. 2. 3. 4.]
[10.  20.  30.  44.4]


In [17]:
x = np.zeros(10, dtype="int")
b = np.ones((3,5), dtype ='float')
c= np.full((3,5), 3.14)
print(x )
print(b)
print(c)
d= np.arange(10,20)
e = np.arange(3,10,2)
f = np.linspace(0,10,5)
print(d , e, f)


[0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
[10 11 12 13 14 15 16 17 18 19] [3 5 7 9] [ 0.   2.5  5.   7.5 10. ]


In [34]:
np.random.random(None)
np.random.random((3,3))
np.random.random(5)
np.random.normal(0, 1,(3,3))
np.random.randint(0,10,(3,3))
np.eye(5)
np.eye(2,4)
np.empty(3)

array([3.5462232e-316, 0.0000000e+000, 1.5810101e-322])